# xingzhi cube 1.54 — hardware pack (ESP32-S3 + ST7789V 240x240)

# --- EXTRA BUTTONS -------------------------------------------------------------
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO39
      mode: INPUT_PULLUP
      inverted: true
    name: "Volume Down"
    id: volume_down
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - media_player.volume_down: external_media_player
    on_release:
      - logger.log: "Volume Down released"

  - platform: gpio
    pin: 
      number: GPIO40
      mode: INPUT_PULLUP
      inverted: true
    name: "Volume Up"
    id: volume_up
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - media_player.volume_up: external_media_player
    on_release:
      - logger.log: "Volume Up released"

# --- CHIP & PSRAM -------------------------------------------------------------
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

# --- BUSES / PERIPHERALS ------------------------------------------------------
spi:
  - id: spi_bus
    clk_pin: 9
    mosi_pin: 10
    # (no MISO line for display)

i2s_audio:
  - id: i2s_mic
    i2s_lrclk_pin: GPIO4   # WS
    i2s_bclk_pin:  GPIO5   # SCK
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin:  GPIO15
    # (no MCLK on this board)

# --- AUDIO DEVICES ------------------------------------------------------------
microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_mic
    i2s_din_pin: GPIO6
    adc_type: external
    channel: left
    pdm: false
    sample_rate: 16000
    bits_per_sample: 16bit

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO7
    dac_type: external
    sample_rate: 16000
    channel: left

# --- BACKLIGHT ----------------------------------------------------------------
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO13
    inverted: false

light:
  - platform: monochromatic
    id: Sled
    name: Screen
    icon: "mdi:television"
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# --- DISPLAY DRIVER (SPI GC9A01A, 240x240 round) ------------------------------
display:
  - platform: ili9xxx
    id: main_display
    model: ST7789V
    spi_id: spi_bus
    cs_pin: 14
    dc_pin: 8
    reset_pin: 18
    invert_colors: true
    data_rate: 40MHz
    update_interval: never
    dimensions:
      height: ${imageheight}
      width: ${imagewidth}
    pages: !include ../display_pages.yaml

# --- BATTERY ADC --------------------------------------------------------------
sensor:
  - platform: adc
    pin: GPIO19
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    accuracy_decimals: 2
    update_interval: 10s
    unit_of_measurement: "V"
    icon: mdi:battery-medium
    filters:
      - multiply: 3.0
      - median:
          window_size: 7
          send_every: 7
          send_first_at: 1
      - throttle: 1min
    on_value:
      then:
        - sensor.template.publish:
            id: battery_percentage
            state: !lambda 'return x;'
